/**
 * Glyph code points from the "Segoe Fluent Icons" system font (Windows 11),
 * with "Segoe MDL2 Assets" as the fallback - both ship with Windows.
 */
export const glyphs = {
  navButton: "\uE700",
  back: "\uE72B",
  chevronDown: "\uE70D",
  chevronUp: "\uE70E",
  openInNewWindow: "\uE8A7",
  add: "\uE710",
  cancel: "\uE711",
  more: "\uE712",
  settings: "\uE713",
  checkMark: "\uE73E",
  delete: "\uE74D",
  volume: "\uE767",
  warning: "\uE7BA",
  play: "\uE768",
  pause: "\uE769",
  rename: "\uE8AC",
  shuffle: "\uE8B1",
  previous: "\uE892",
  next: "\uE893",
  repeatOne: "\uE8ED",
  repeatAll: "\uE8EE",
  bulletedList: "\uE8FD",
  library: "\uE8F1",
  musicAlbum: "\uE93C",
  musicNote: "\uEC4F",
} as const;